{
  "issue_type": "bug",
  "extracted_from": "/root/yunwei37/vllm-exp/bug-study/analysis_llm/sample_results/vllm/label_based/bug/issues.json",
  "issue": {
    "number": 13054,
    "title": "[Bug]: RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead. on Gaudi2",
    "body": "### Your current environment\n\n<details>\n<summary>The output of `python collect_env.py`</summary>\n\n```text\nAutomatically detected platform hpu.\nCollecting environment information...\nPyTorch version: 2.5.1a0+git6fc067b\nIs debug build: False\nCUDA used to build PyTorch: None\nROCM used to build PyTorch: N/A\n\nOS: Ubuntu 22.04.5 LTS (x86_64)\nGCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0\nClang version: Could not collect\nCMake version: version 3.22.1\nLibc version: glibc-2.35\n\nPython version: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (64-bit runtime)\nPython platform: Linux-5.15.0-122-generic-x86_64-with-glibc2.35\nIs CUDA available: False\nCUDA runtime version: No CUDA\nCUDA_MODULE_LOADING set to: N/A\nGPU models and configuration: No CUDA\nNvidia driver version: No CUDA\ncuDNN version: No CUDA\nHIP runtime version: N/A\nMIOpen runtime version: N/A\nIs XNNPACK available: True\n\nCPU:\nArchitecture:                         x86_64\nCPU op-mode(s):                       32-bit, 64-bit\nAddress sizes:                        46 bits physical, 57 bits virtual\nByte Order:                           Little Endian\nCPU(s):                               160\nOn-line CPU(s) list:                  0-159\nVendor ID:                            GenuineIntel\nModel name:                           Intel(R) Xeon(R) Platinum 8380 CPU @ 2.30GHz\nCPU family:                           6\nModel:                                106\nThread(s) per core:                   2\nCore(s) per socket:                   40\nSocket(s):                            2\nStepping:                             6\nCPU max MHz:                          3400.0000\nCPU min MHz:                          800.0000\nBogoMIPS:                             4600.00\nFlags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities\nVirtualization:                       VT-x\nL1d cache:                            3.8 MiB (80 instances)\nL1i cache:                            2.5 MiB (80 instances)\nL2 cache:                             100 MiB (80 instances)\nL3 cache:                             120 MiB (2 instances)\nNUMA node(s):                         2\nNUMA node0 CPU(s):                    0-39,80-119\nNUMA node1 CPU(s):                    40-79,120-159\nVulnerability Gather data sampling:   Mitigation; Microcode\nVulnerability Itlb multihit:          Not affected\nVulnerability L1tf:                   Not affected\nVulnerability Mds:                    Not affected\nVulnerability Meltdown:               Not affected\nVulnerability Mmio stale data:        Mitigation; Clear CPU buffers; SMT vulnerable\nVulnerability Reg file data sampling: Not affected\nVulnerability Retbleed:               Not affected\nVulnerability Spec rstack overflow:   Not affected\nVulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp\nVulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization\nVulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop\nVulnerability Srbds:                  Not affected\nVulnerability Tsx async abort:        Not affected\n\nVersions of relevant libraries:\n[pip3] habana-torch-dataloader==1.19.1.26\n[pip3] habana-torch-plugin==1.19.1.26\n[pip3] numpy==1.26.4\n[pip3] pynvml==8.0.4\n[pip3] pytorch-lightning==2.5.0.post0\n[pip3] pyzmq==26.2.1\n[pip3] torch==2.5.1a0+git6fc067b\n[pip3] torch_tb_profiler==0.4.0\n[pip3] torchaudio==2.5.1a0+1661daf\n[pip3] torchdata==0.9.0+d4bb3e6\n[pip3] torchmetrics==1.6.1\n[pip3] torchtext==0.18.0a0+9bed85d\n[pip3] torchvision==0.20.1a0+3ac97aa\n[pip3] transformers==4.48.2\n[pip3] triton==3.1.0\n[conda] Could not collect\nROCM Version: Could not collect\nNeuron SDK Version: N/A\nvLLM Version: 0.7.2\nvLLM Build Flags:\nCUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled\nGPU Topology:\nCould not collect\n\nLD_LIBRARY_PATH=/opt/habanalabs/libfabric-1.22.0/lib:/opt/amazon/openmpi/lib:/usr/lib/habanalabs:\nVLLM_NO_USAGE_STATS=1\nVLLM_TARGET_DEVICE=hpu\nNCCL_CUMEM_ENABLE=0\nTORCHINDUCTOR_COMPILE_THREADS=1\n```\n\n</details>\n\n\n### \ud83d\udc1b Describe the bug\n\nBuild vLLM using: \n```\ndocker build -t vllm-hpu:v0.7.2-mainline -f Dockerfile.hpu .\n```\n\nThen run it using:\n\n```\n\"cd /workspace/vllm && pip install git+https://github.com/huggingface/transformers accelerate && pip install qwen-vl-utils[decord]==0.0.8 && vllm serve Qwen/Qwen2.5-VL-7B-Instruct --disable_log_requests --port 8080 --tensor-parallel-size 2\"\n```\n\nThe hardware is a node with 8 Gaudi 2 HL-225H mezzanine cards with 2x Xeon 8380 Processors. The container has 2 Gaudi 2 cards, 70Gi memory and 25Gi of hugepages-2Mi assigned to it.\n\n```text\nview size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/engine/multiprocessing/engine.py\", line 380, in run_mp_engine\n    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/engine/multiprocessing/engine.py\", line 123, in from_engine_args\n    return cls(ipc_path=ipc_path,\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/engine/multiprocessing/engine.py\", line 75, in __init__\n    self.engine = LLMEngine(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/engine/llm_engine.py\", line 276, in __init__\n    self._initialize_kv_caches()\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/engine/llm_engine.py\", line 416, in _initialize_kv_caches\n    self.model_executor.determine_num_available_blocks())\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/executor/executor_base.py\", line 101, in determine_num_available_blocks\n    results = self.collective_rpc(\"determine_num_available_blocks\")\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/executor/executor_base.py\", line 307, in collective_rpc\n    return self._run_workers(method, *args, **(kwargs or {}))\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/executor/mp_distributed_executor.py\", line 185, in _run_workers\n    driver_worker_output = run_method(self.driver_worker, sent_method,\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/utils.py\", line 2220, in run_method\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/worker/hpu_worker.py\", line 214, in determine_num_available_blocks\n    self.model_runner.profile_run()\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/worker/hpu_model_runner.py\", line 1311, in profile_run\n    self.warmup_scenario(max_batch_size, max_seq_len, True, kv_caches,\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/worker/hpu_model_runner.py\", line 1383, in warmup_scenario\n    self.execute_model(inputs, kv_caches, warmup_mode=True)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 116, in decorate_context\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/worker/hpu_model_runner.py\", line 1967, in execute_model\n    hidden_states = self.model.forward(\n  File \"/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py\", line 736, in forward\n    return wrapped_hpugraph_forward(\n  File \"/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py\", line 586, in wrapped_hpugraph_forward\n    return orig_fwd(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/worker/hpu_model_runner.py\", line 371, in forward\n    hidden_states = self.model(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1739, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1750, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/model_executor/models/qwen2_5_vl.py\", line 1095, in forward\n    hidden_states = self.language_model.model(\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/compilation/decorators.py\", line 172, in __call__\n    return self.forward(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/model_executor/models/qwen2.py\", line 348, in forward\n    hidden_states, residual = layer(\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1739, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1847, in _call_impl\n    return inner()\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1793, in inner\n    result = forward_call(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/model_executor/models/qwen2.py\", line 247, in forward\n    hidden_states = self.self_attn(\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1739, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1847, in _call_impl\n    return inner()\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1793, in inner\n    result = forward_call(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/model_executor/models/qwen2.py\", line 178, in forward\n    q, k = self.rotary_emb(positions, q, k)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1739, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1847, in _call_impl\n    return inner()\n  File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1793, in inner\n    result = forward_call(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/model_executor/layers/rotary_embedding.py\", line 822, in forward\n    query = query.view(num_tokens, -1, self.head_size)\nRuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.\nTraceback (most recent call last):\n  File \"/usr/local/bin/vllm\", line 33, in <module>\n    sys.exit(load_entry_point('vllm==0.7.2+gaudi000', 'console_scripts', 'vllm')())\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/scripts.py\", line 204, in main\n    args.dispatch_function(args)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/scripts.py\", line 44, in serve\n    uvloop.run(run_server(args))\n  File \"/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py\", line 82, in run\n    return loop.run_until_complete(wrapper())\n  File \"uvloop/loop.pyx\", line 1518, in uvloop.loop.Loop.run_until_complete\n  File \"/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py\", line 61, in wrapper\n    return await main\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py\", line 875, in run_server\n    async with build_async_engine_client(args) as engine_client:\n  File \"/usr/lib/python3.10/contextlib.py\", line 199, in __aenter__\n    return await anext(self.gen)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py\", line 136, in build_async_engine_client\n    async with build_async_engine_client_from_engine_args(\n  File \"/usr/lib/python3.10/contextlib.py\", line 199, in __aenter__\n    return await anext(self.gen)\n  File \"/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py\", line 230, in build_async_engine_client_from_engine_args\n    raise RuntimeError(\nRuntimeError: Engine process failed to start. See stack trace for the root cause.\n```\n\n### Before submitting a new issue...\n\n- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.",
    "labels": [
      "bug",
      "stale"
    ],
    "state": "open",
    "created_at": "2025-02-10T20:28:41+00:00",
    "closed_at": null,
    "comments": 3,
    "reactions": {
      "url": "https://api.github.com/repos/vllm-project/vllm/issues/13054/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "author_association": "NONE",
    "html_url": "https://github.com/vllm-project/vllm/issues/13054"
  }
}